# coding: utf-8

# flake8: noqa

"""
    Skautik Partner API

    The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# The hand-designed client. See skautikhq/skautik-sdk.
from skautik.client import Skautik

# Define package exports
__all__ = [
    "AccountAndStatusApi",
    "ExportsApi",
    "ImageGenerationsApi",
    "ImportsApi",
    "InquiriesApi",
    "MarketsApi",
    "PropertiesApi",
    "WebhooksApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Address",
    "Bounds",
    "Building",
    "City",
    "CityList",
    "ConnectorInput",
    "Delivery",
    "DeliveryInput",
    "DeliveryList",
    "Descriptions",
    "District",
    "DistrictList",
    "Energy",
    "Envelope",
    "Export",
    "ExportInput",
    "ExportList",
    "ExportResponse",
    "Features",
    "Generation",
    "GenerationInput",
    "GenerationList",
    "GenerationResponse",
    "Image",
    "ImageInput",
    "ImageList",
    "ImageResponse",
    "ImportCounts",
    "ImportList",
    "ImportRecord",
    "ImportRecordList",
    "ImportResponse",
    "ImportSource",
    "ImportSourceInput",
    "ImportSourceList",
    "ImportSourceResponse",
    "Inquiry",
    "InquiryPage",
    "InquiryResponse",
    "InquiryStatusInput",
    "Listing",
    "ListingInput",
    "Location",
    "Market",
    "MarketContext",
    "MarketMetric",
    "MarketResponse",
    "ModelImport",
    "ModelProperty",
    "PageMeta",
    "Parking",
    "PriceObservation",
    "PriceObservationList",
    "Problem",
    "ProblemErrorsInner",
    "PropertyInput",
    "PropertyList",
    "PropertyPage",
    "PropertyResponse",
    "Rooms",
    "SearchFilters",
    "SearchRequest",
    "Series",
    "SeriesPoint",
    "SeriesResponse",
    "ShrinkGuard",
    "Size",
    "SourceDelivery",
    "SourceUpdate",
    "Translation",
    "Webhook",
    "WebhookInput",
    "WebhookList",
    "WebhookResponse",
    "WebhookUpdate",
]

# import apis into sdk package
from skautik.api.account_and_status_api import AccountAndStatusApi as AccountAndStatusApi
from skautik.api.exports_api import ExportsApi as ExportsApi
from skautik.api.image_generations_api import ImageGenerationsApi as ImageGenerationsApi
from skautik.api.imports_api import ImportsApi as ImportsApi
from skautik.api.inquiries_api import InquiriesApi as InquiriesApi
from skautik.api.markets_api import MarketsApi as MarketsApi
from skautik.api.properties_api import PropertiesApi as PropertiesApi
from skautik.api.webhooks_api import WebhooksApi as WebhooksApi

# import ApiClient
from skautik.api_response import ApiResponse as ApiResponse
from skautik.api_client import ApiClient as ApiClient
from skautik.configuration import Configuration as Configuration
from skautik.exceptions import OpenApiException as OpenApiException
from skautik.exceptions import ApiTypeError as ApiTypeError
from skautik.exceptions import ApiValueError as ApiValueError
from skautik.exceptions import ApiKeyError as ApiKeyError
from skautik.exceptions import ApiAttributeError as ApiAttributeError
from skautik.exceptions import ApiException as ApiException

# import models into sdk package
from skautik.models.address import Address as Address
from skautik.models.bounds import Bounds as Bounds
from skautik.models.building import Building as Building
from skautik.models.city import City as City
from skautik.models.city_list import CityList as CityList
from skautik.models.connector_input import ConnectorInput as ConnectorInput
from skautik.models.delivery import Delivery as Delivery
from skautik.models.delivery_input import DeliveryInput as DeliveryInput
from skautik.models.delivery_list import DeliveryList as DeliveryList
from skautik.models.descriptions import Descriptions as Descriptions
from skautik.models.district import District as District
from skautik.models.district_list import DistrictList as DistrictList
from skautik.models.energy import Energy as Energy
from skautik.models.envelope import Envelope as Envelope
from skautik.models.export import Export as Export
from skautik.models.export_input import ExportInput as ExportInput
from skautik.models.export_list import ExportList as ExportList
from skautik.models.export_response import ExportResponse as ExportResponse
from skautik.models.features import Features as Features
from skautik.models.generation import Generation as Generation
from skautik.models.generation_input import GenerationInput as GenerationInput
from skautik.models.generation_list import GenerationList as GenerationList
from skautik.models.generation_response import GenerationResponse as GenerationResponse
from skautik.models.image import Image as Image
from skautik.models.image_input import ImageInput as ImageInput
from skautik.models.image_list import ImageList as ImageList
from skautik.models.image_response import ImageResponse as ImageResponse
from skautik.models.import_counts import ImportCounts as ImportCounts
from skautik.models.import_list import ImportList as ImportList
from skautik.models.import_record import ImportRecord as ImportRecord
from skautik.models.import_record_list import ImportRecordList as ImportRecordList
from skautik.models.import_response import ImportResponse as ImportResponse
from skautik.models.import_source import ImportSource as ImportSource
from skautik.models.import_source_input import ImportSourceInput as ImportSourceInput
from skautik.models.import_source_list import ImportSourceList as ImportSourceList
from skautik.models.import_source_response import ImportSourceResponse as ImportSourceResponse
from skautik.models.inquiry import Inquiry as Inquiry
from skautik.models.inquiry_page import InquiryPage as InquiryPage
from skautik.models.inquiry_response import InquiryResponse as InquiryResponse
from skautik.models.inquiry_status_input import InquiryStatusInput as InquiryStatusInput
from skautik.models.listing import Listing as Listing
from skautik.models.listing_input import ListingInput as ListingInput
from skautik.models.location import Location as Location
from skautik.models.market import Market as Market
from skautik.models.market_context import MarketContext as MarketContext
from skautik.models.market_metric import MarketMetric as MarketMetric
from skautik.models.market_response import MarketResponse as MarketResponse
from skautik.models.model_import import ModelImport as ModelImport
from skautik.models.model_property import ModelProperty as ModelProperty
from skautik.models.page_meta import PageMeta as PageMeta
from skautik.models.parking import Parking as Parking
from skautik.models.price_observation import PriceObservation as PriceObservation
from skautik.models.price_observation_list import PriceObservationList as PriceObservationList
from skautik.models.problem import Problem as Problem
from skautik.models.problem_errors_inner import ProblemErrorsInner as ProblemErrorsInner
from skautik.models.property_input import PropertyInput as PropertyInput
from skautik.models.property_list import PropertyList as PropertyList
from skautik.models.property_page import PropertyPage as PropertyPage
from skautik.models.property_response import PropertyResponse as PropertyResponse
from skautik.models.rooms import Rooms as Rooms
from skautik.models.search_filters import SearchFilters as SearchFilters
from skautik.models.search_request import SearchRequest as SearchRequest
from skautik.models.series import Series as Series
from skautik.models.series_point import SeriesPoint as SeriesPoint
from skautik.models.series_response import SeriesResponse as SeriesResponse
from skautik.models.shrink_guard import ShrinkGuard as ShrinkGuard
from skautik.models.size import Size as Size
from skautik.models.source_delivery import SourceDelivery as SourceDelivery
from skautik.models.source_update import SourceUpdate as SourceUpdate
from skautik.models.translation import Translation as Translation
from skautik.models.webhook import Webhook as Webhook
from skautik.models.webhook_input import WebhookInput as WebhookInput
from skautik.models.webhook_list import WebhookList as WebhookList
from skautik.models.webhook_response import WebhookResponse as WebhookResponse
from skautik.models.webhook_update import WebhookUpdate as WebhookUpdate

