# Code generated by skautikhq/skautik-sdk. DO NOT EDIT.

"""The Skautik API.

    from skautik import Skautik

    skautik = Skautik(api_key="sk_live_...")

    page = skautik.properties.list(city="Berlin", max_price=750_000)

    for property in skautik.properties.list_all(city="Berlin"):
        print(property.title, property.listing.price)
"""

from __future__ import annotations

from typing import Any, Iterator, Optional

from skautik.api_client import ApiClient
from skautik.configuration import Configuration
from skautik.api.account_and_status_api import AccountAndStatusApi
from skautik.api.exports_api import ExportsApi
from skautik.api.image_generations_api import ImageGenerationsApi
from skautik.api.imports_api import ImportsApi
from skautik.api.inquiries_api import InquiriesApi
from skautik.api.markets_api import MarketsApi
from skautik.api.properties_api import PropertiesApi
from skautik.api.webhooks_api import WebhooksApi


class Skautik:
    """A client for the Skautik API.

    Pass an API key from the developer console. Everything else has a working
    default, and host is there for pointing at a local or staging server.
    """

    def __init__(
        self,
        api_key: str,
        *,
        host: Optional[str] = None,
        configuration: Optional[Configuration] = None,
    ) -> None:
        if configuration is None:
            configuration = Configuration()
        if host is not None:
            configuration.host = host

        configuration.access_token = api_key

        self._api_client = ApiClient(configuration)

        self.account = AccountResource(self._api_client)
        """Endpoints about your key rather than about property."""

        self.exports = ExportsResource(self._api_client)
        """Bulk extracts for volumes that would be unreasonable to page through. An export is asynchronous: you request one, we build it, and you fetch the file when it is ready."""

        self.generations = GenerationsResource(self._api_client)
        """Transform a photograph you have already uploaded: stage an empty room, remove clutter, or correct how a picture was taken. Each request is queued and produced in the background."""

        self.imports = ImportsResource(self._api_client)
        """Move inventory in from whatever system already holds it. A one-off import handles a migration; an import source keeps a CRM and Skautik in step indefinitely."""

        self.inquiries = InquiriesResource(self._api_client)
        """Enquiries people have made about your properties, and the state you have moved each one to. Scoped to the properties your organisation owns: an enquiry belongs to whoever owns the property it is about."""

        self.markets = MarketsResource(self._api_client)
        """Where we have coverage, how each market is subdivided, and the aggregate statistics computed across it."""

        self.properties = PropertiesResource(self._api_client)
        """The catalogue, and your own inventory within it. Read endpoints span everything we hold; write endpoints only ever touch records your organisation published."""

        self.webhooks = WebhooksResource(self._api_client)
        """Subscribe to changes rather than polling for them. A webhook costs nothing against your request quota, which makes it much cheaper than re-reading a market on a timer."""

    @property
    def api_client(self) -> ApiClient:
        """The generated client underneath, for anything this does not cover."""
        return self._api_client

    def __enter__(self) -> "Skautik":
        return self

    def __exit__(self, *exception: Any) -> None:
        self._api_client.close()


def _page_through(fetch, **arguments) -> Iterator[Any]:
    """Walk a cursor-paged endpoint, yielding records.

    Stops when the API says there are no more, rather than when a page comes
    back short: a full page can still be the last one, and a short page can
    still carry a cursor. Reading has_more is the only correct test, and
    writing it once here is why this exists.
    """
    cursor = None

    while True:
        page = fetch(**arguments, cursor=cursor) if cursor else fetch(**arguments)

        for record in page.data:
            yield record

        meta = getattr(page, "meta", None)
        if meta is None or not getattr(meta, "has_more", False):
            return

        following = getattr(meta, "next_cursor", None)
        # A cursor that does not move would page for ever over one page, which
        # is a server fault and should not become a client that never returns.
        if not following or following == cursor:
            return
        cursor = following


class AccountResource:
    """Endpoints about your key rather than about property."""

    def __init__(self, api_client: ApiClient) -> None:
        self._api = AccountAndStatusApi(api_client)

    def get_health(self, *arguments: Any, **keywords: Any) -> Any:
        """Service status"""
        return self._api.get_health(*arguments, **keywords)

    def get_me(self, *arguments: Any, **keywords: Any) -> Any:
        """Key introspection

        Requires the `properties:read` scope."""
        return self._api.get_me(*arguments, **keywords)

class ExportsResource:
    """Bulk extracts for volumes that would be unreasonable to page through. An export is asynchronous: you request one, we build it, and you fetch the file when it is ready."""

    def __init__(self, api_client: ApiClient) -> None:
        self._api = ExportsApi(api_client)

    def list(self, *arguments: Any, **keywords: Any) -> Any:
        """List exports

        Requires the `exports:create` scope."""
        return self._api.list_exports(*arguments, **keywords)

    def create(self, *arguments: Any, **keywords: Any) -> Any:
        """Request an export

        Requires the `exports:create` scope."""
        return self._api.create_export(*arguments, **keywords)

    def get(self, *arguments: Any, **keywords: Any) -> Any:
        """Retrieve an export

        Requires the `exports:create` scope."""
        return self._api.get_export(*arguments, **keywords)

class GenerationsResource:
    """Transform a photograph you have already uploaded: stage an empty room, remove clutter, or correct how a picture was taken. Each request is queued and produced in the background."""

    def __init__(self, api_client: ApiClient) -> None:
        self._api = ImageGenerationsApi(api_client)

    def list(self, *arguments: Any, **keywords: Any) -> Any:
        """List generations

        Requires the `images:write` scope."""
        return self._api.list_generations(*arguments, **keywords)

    def create(self, *arguments: Any, **keywords: Any) -> Any:
        """Request a generation

        Requires the `images:write` scope."""
        return self._api.create_generation(*arguments, **keywords)

    def get(self, *arguments: Any, **keywords: Any) -> Any:
        """Retrieve a generation

        Requires the `images:write` scope."""
        return self._api.get_generation(*arguments, **keywords)

    def list_kinds(self, *arguments: Any, **keywords: Any) -> Any:
        """List what can be generated

        Requires the `images:write` scope."""
        return self._api.list_generation_kinds(*arguments, **keywords)

class ImportsResource:
    """Move inventory in from whatever system already holds it. A one-off import handles a migration; an import source keeps a CRM and Skautik in step indefinitely."""

    def __init__(self, api_client: ApiClient) -> None:
        self._api = ImportsApi(api_client)

    def list_sources(self, *arguments: Any, **keywords: Any) -> Any:
        """List import sources

        Requires the `imports:write` scope."""
        return self._api.list_import_sources(*arguments, **keywords)

    def create_source(self, *arguments: Any, **keywords: Any) -> Any:
        """Create an import source

        Requires the `imports:write` scope."""
        return self._api.create_import_source(*arguments, **keywords)

    def delete_source(self, *arguments: Any, **keywords: Any) -> Any:
        """Delete an import source

        Requires the `imports:write` scope."""
        return self._api.delete_import_source(*arguments, **keywords)

    def get_source(self, *arguments: Any, **keywords: Any) -> Any:
        """Retrieve an import source

        Requires the `imports:write` scope."""
        return self._api.get_import_source(*arguments, **keywords)

    def update_source(self, *arguments: Any, **keywords: Any) -> Any:
        """Update an import source

        Requires the `imports:write` scope."""
        return self._api.update_import_source(*arguments, **keywords)

    def list(self, *arguments: Any, **keywords: Any) -> Any:
        """List imports

        Requires the `imports:write` scope."""
        return self._api.list_imports(*arguments, **keywords)

    def create(self, *arguments: Any, **keywords: Any) -> Any:
        """Start an import

        Requires the `imports:write` scope."""
        return self._api.create_import(*arguments, **keywords)

    def get(self, *arguments: Any, **keywords: Any) -> Any:
        """Retrieve an import

        Requires the `imports:write` scope."""
        return self._api.get_import(*arguments, **keywords)

    def list_records(self, *arguments: Any, **keywords: Any) -> Any:
        """List import records

        Requires the `imports:write` scope."""
        return self._api.list_import_records(*arguments, **keywords)

    def formats(self, *arguments: Any, **keywords: Any) -> Any:
        """List accepted formats and columns

        Requires the `imports:write` scope."""
        return self._api.import_formats(*arguments, **keywords)

class InquiriesResource:
    """Enquiries people have made about your properties, and the state you have moved each one to. Scoped to the properties your organisation owns: an enquiry belongs to whoever owns the property it is about."""

    def __init__(self, api_client: ApiClient) -> None:
        self._api = InquiriesApi(api_client)

    def list(self, *arguments: Any, **keywords: Any) -> Any:
        """List inquiries

        Requires the `inquiries:read` scope."""
        return self._api.list_inquiries(*arguments, **keywords)

    def list_all(self, **keywords: Any) -> Iterator[Any]:
        """Every record, following the cursor.

        The same request as `list`, with the paging done for you: it yields
        records rather than pages and stops when the API says there are no
        more. Nothing is held beyond the page being read.
        """
        return _page_through(self._api.list_inquiries, **keywords)

    def get(self, *arguments: Any, **keywords: Any) -> Any:
        """Retrieve an inquiry

        Requires the `inquiries:read` scope."""
        return self._api.get_inquiry(*arguments, **keywords)

    def update(self, *arguments: Any, **keywords: Any) -> Any:
        """Set the status

        Requires the `inquiries:read` scope."""
        return self._api.update_inquiry(*arguments, **keywords)

    def mark_read(self, *arguments: Any, **keywords: Any) -> Any:
        """Mark as read

        Requires the `inquiries:read` scope."""
        return self._api.mark_inquiry_read(*arguments, **keywords)

class MarketsResource:
    """Where we have coverage, how each market is subdivided, and the aggregate statistics computed across it."""

    def __init__(self, api_client: ApiClient) -> None:
        self._api = MarketsApi(api_client)

    def list(self, *arguments: Any, **keywords: Any) -> Any:
        """List markets

        Requires the `markets:read` scope."""
        return self._api.list_markets(*arguments, **keywords)

    def get(self, *arguments: Any, **keywords: Any) -> Any:
        """Retrieve a market

        Requires the `markets:read` scope."""
        return self._api.get_market(*arguments, **keywords)

    def list_districts(self, *arguments: Any, **keywords: Any) -> Any:
        """List districts

        Requires the `markets:read` scope."""
        return self._api.list_districts(*arguments, **keywords)

    def get_district(self, *arguments: Any, **keywords: Any) -> Any:
        """Retrieve a district

        Requires the `markets:read` scope."""
        return self._api.get_district(*arguments, **keywords)

    def statistics(self, *arguments: Any, **keywords: Any) -> Any:
        """Market statistics

        Requires the `markets:read` scope."""
        return self._api.market_statistics(*arguments, **keywords)

class PropertiesResource:
    """The catalogue, and your own inventory within it. Read endpoints span everything we hold; write endpoints only ever touch records your organisation published."""

    def __init__(self, api_client: ApiClient) -> None:
        self._api = PropertiesApi(api_client)

    def list(self, *arguments: Any, **keywords: Any) -> Any:
        """List properties

        Requires the `properties:read` scope."""
        return self._api.list_properties(*arguments, **keywords)

    def list_all(self, **keywords: Any) -> Iterator[Any]:
        """Every record, following the cursor.

        The same request as `list`, with the paging done for you: it yields
        records rather than pages and stops when the API says there are no
        more. Nothing is held beyond the page being read.
        """
        return _page_through(self._api.list_properties, **keywords)

    def create(self, *arguments: Any, **keywords: Any) -> Any:
        """Create a property

        Requires the `properties:write` scope."""
        return self._api.create_property(*arguments, **keywords)

    def delete(self, *arguments: Any, **keywords: Any) -> Any:
        """Withdraw a property

        Requires the `properties:write` scope."""
        return self._api.delete_property(*arguments, **keywords)

    def get(self, *arguments: Any, **keywords: Any) -> Any:
        """Retrieve a property

        Requires the `properties:read` scope."""
        return self._api.get_property(*arguments, **keywords)

    def update(self, *arguments: Any, **keywords: Any) -> Any:
        """Update a property

        Requires the `properties:write` scope."""
        return self._api.update_property(*arguments, **keywords)

    def list_images(self, *arguments: Any, **keywords: Any) -> Any:
        """List images

        Requires the `properties:read` scope."""
        return self._api.list_property_images(*arguments, **keywords)

    def upload_image(self, *arguments: Any, **keywords: Any) -> Any:
        """Upload an image

        Requires the `images:write` scope."""
        return self._api.upload_property_image(*arguments, **keywords)

    def delete_image(self, *arguments: Any, **keywords: Any) -> Any:
        """Delete an image

        Requires the `images:write` scope."""
        return self._api.delete_property_image(*arguments, **keywords)

    def price_history(self, *arguments: Any, **keywords: Any) -> Any:
        """Price history

        Requires the `properties:read` scope."""
        return self._api.property_price_history(*arguments, **keywords)

    def similar(self, *arguments: Any, **keywords: Any) -> Any:
        """Similar properties

        Requires the `properties:read` scope."""
        return self._api.similar_properties(*arguments, **keywords)

    def search(self, *arguments: Any, **keywords: Any) -> Any:
        """Search properties

        Requires the `properties:read` scope."""
        return self._api.search_properties(*arguments, **keywords)

class WebhooksResource:
    """Subscribe to changes rather than polling for them. A webhook costs nothing against your request quota, which makes it much cheaper than re-reading a market on a timer."""

    def __init__(self, api_client: ApiClient) -> None:
        self._api = WebhooksApi(api_client)

    def list(self, *arguments: Any, **keywords: Any) -> Any:
        """List webhooks

        Requires the `webhooks:manage` scope."""
        return self._api.list_webhooks(*arguments, **keywords)

    def create(self, *arguments: Any, **keywords: Any) -> Any:
        """Create a webhook

        Requires the `webhooks:manage` scope."""
        return self._api.create_webhook(*arguments, **keywords)

    def delete(self, *arguments: Any, **keywords: Any) -> Any:
        """Delete a webhook

        Requires the `webhooks:manage` scope."""
        return self._api.delete_webhook(*arguments, **keywords)

    def get(self, *arguments: Any, **keywords: Any) -> Any:
        """Retrieve a webhook

        Requires the `webhooks:manage` scope."""
        return self._api.get_webhook(*arguments, **keywords)

    def update(self, *arguments: Any, **keywords: Any) -> Any:
        """Update a webhook

        Requires the `webhooks:manage` scope."""
        return self._api.update_webhook(*arguments, **keywords)

    def list_deliveries(self, *arguments: Any, **keywords: Any) -> Any:
        """List deliveries

        Requires the `webhooks:manage` scope."""
        return self._api.list_deliveries(*arguments, **keywords)

    def rotate_secret(self, *arguments: Any, **keywords: Any) -> Any:
        """Rotate the signing secret

        Requires the `webhooks:manage` scope."""
        return self._api.rotate_webhook_secret(*arguments, **keywords)

    def test(self, *arguments: Any, **keywords: Any) -> Any:
        """Send a test delivery

        Requires the `webhooks:manage` scope."""
        return self._api.test_webhook(*arguments, **keywords)

    def list_events(self, *arguments: Any, **keywords: Any) -> Any:
        """List available events

        Requires the `webhooks:manage` scope."""
        return self._api.list_webhook_events(*arguments, **keywords)
