# coding: utf-8

# flake8: noqa
"""
    Skautik Partner API

    The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from skautik.models.address import Address
from skautik.models.building import Building
from skautik.models.city import City
from skautik.models.create_export_request import CreateExportRequest
from skautik.models.create_generation_request import CreateGenerationRequest
from skautik.models.create_import_source_request import CreateImportSourceRequest
from skautik.models.create_property_request import CreatePropertyRequest
from skautik.models.create_webhook_request import CreateWebhookRequest
from skautik.models.delivery import Delivery
from skautik.models.district import District
from skautik.models.energy import Energy
from skautik.models.envelope import Envelope
from skautik.models.export import Export
from skautik.models.generation import Generation
from skautik.models.image import Image
from skautik.models.import_counts import ImportCounts
from skautik.models.import_record import ImportRecord
from skautik.models.import_source import ImportSource
from skautik.models.inquiry import Inquiry
from skautik.models.listing import Listing
from skautik.models.location import Location
from skautik.models.market import Market
from skautik.models.market_context import MarketContext
from skautik.models.market_metric import MarketMetric
from skautik.models.model_import import ModelImport
from skautik.models.model_property import ModelProperty
from skautik.models.price_observation import PriceObservation
from skautik.models.problem import Problem
from skautik.models.problem_errors_inner import ProblemErrorsInner
from skautik.models.rooms import Rooms
from skautik.models.search_properties_request import SearchPropertiesRequest
from skautik.models.series import Series
from skautik.models.series_point import SeriesPoint
from skautik.models.size import Size
from skautik.models.source_delivery import SourceDelivery
from skautik.models.update_inquiry_request import UpdateInquiryRequest
from skautik.models.update_webhook_request import UpdateWebhookRequest
from skautik.models.webhook import Webhook

