# coding: utf-8

# flake8: noqa
"""
    Skautik Partner API

    The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from skautik.models.create_export_request import CreateExportRequest
from skautik.models.create_generation_request import CreateGenerationRequest
from skautik.models.create_import_source_request import CreateImportSourceRequest
from skautik.models.create_property_request import CreatePropertyRequest
from skautik.models.create_webhook_request import CreateWebhookRequest
from skautik.models.envelope import Envelope
from skautik.models.problem import Problem
from skautik.models.problem_errors_inner import ProblemErrorsInner
from skautik.models.search_properties_request import SearchPropertiesRequest
from skautik.models.update_inquiry_request import UpdateInquiryRequest
from skautik.models.update_webhook_request import UpdateWebhookRequest

