# coding: utf-8

# flake8: noqa
"""
    Skautik Partner API

    The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from skautik.models.address import Address
from skautik.models.bounds import Bounds
from skautik.models.building import Building
from skautik.models.city import City
from skautik.models.city_list import CityList
from skautik.models.delivery import Delivery
from skautik.models.delivery_input import DeliveryInput
from skautik.models.delivery_list import DeliveryList
from skautik.models.district import District
from skautik.models.district_list import DistrictList
from skautik.models.energy import Energy
from skautik.models.envelope import Envelope
from skautik.models.export import Export
from skautik.models.export_input import ExportInput
from skautik.models.export_list import ExportList
from skautik.models.export_response import ExportResponse
from skautik.models.generation import Generation
from skautik.models.generation_input import GenerationInput
from skautik.models.generation_list import GenerationList
from skautik.models.generation_response import GenerationResponse
from skautik.models.image import Image
from skautik.models.image_list import ImageList
from skautik.models.image_response import ImageResponse
from skautik.models.import_counts import ImportCounts
from skautik.models.import_list import ImportList
from skautik.models.import_record import ImportRecord
from skautik.models.import_record_list import ImportRecordList
from skautik.models.import_response import ImportResponse
from skautik.models.import_source import ImportSource
from skautik.models.import_source_input import ImportSourceInput
from skautik.models.import_source_list import ImportSourceList
from skautik.models.import_source_response import ImportSourceResponse
from skautik.models.inquiry import Inquiry
from skautik.models.inquiry_page import InquiryPage
from skautik.models.inquiry_response import InquiryResponse
from skautik.models.inquiry_status_input import InquiryStatusInput
from skautik.models.listing import Listing
from skautik.models.listing_input import ListingInput
from skautik.models.location import Location
from skautik.models.market import Market
from skautik.models.market_context import MarketContext
from skautik.models.market_metric import MarketMetric
from skautik.models.market_response import MarketResponse
from skautik.models.model_import import ModelImport
from skautik.models.model_property import ModelProperty
from skautik.models.page_meta import PageMeta
from skautik.models.price_observation import PriceObservation
from skautik.models.price_observation_list import PriceObservationList
from skautik.models.problem import Problem
from skautik.models.problem_errors_inner import ProblemErrorsInner
from skautik.models.property_input import PropertyInput
from skautik.models.property_list import PropertyList
from skautik.models.property_page import PropertyPage
from skautik.models.property_response import PropertyResponse
from skautik.models.rooms import Rooms
from skautik.models.search_filters import SearchFilters
from skautik.models.search_request import SearchRequest
from skautik.models.series import Series
from skautik.models.series_point import SeriesPoint
from skautik.models.series_response import SeriesResponse
from skautik.models.size import Size
from skautik.models.source_delivery import SourceDelivery
from skautik.models.source_update import SourceUpdate
from skautik.models.webhook import Webhook
from skautik.models.webhook_input import WebhookInput
from skautik.models.webhook_list import WebhookList
from skautik.models.webhook_response import WebhookResponse
from skautik.models.webhook_update import WebhookUpdate

