# coding: utf-8

"""
    Skautik Partner API

    The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateImportSourceRequest(BaseModel):
    """
    CreateImportSourceRequest
    """ # noqa: E501
    deletion_policy: Optional[StrictStr] = Field(default='explicit_only', description="explicit_only honours deletion markers alone. absence_withdraws also withdraws anything missing from a full delivery, and should only be used where the format is a complete statement of stock.", json_schema_extra={"examples": ["explicit_only"]})
    delivery: Dict[str, Any] = Field(description="How data arrives. fetch_url pulls from a URL you give us on a schedule; api_push means you send us each delivery. SFTP drops are named in the schema and are not running yet, so asking for one is refused rather than answered with credentials for a host that would never accept them.", json_schema_extra={"examples": [{"compression": "gzip", "url": "https://example.com/hooks/skautik"}]})
    format: StrictStr = Field(description="Format this source delivers. Only csv and json parse today; the others are named in the schema and are refused here rather than accepted into a connector that would fail every run.", json_schema_extra={"examples": ["csv"]})
    mapping: Optional[Dict[str, Any]] = Field(default=None, description="Field mapping, for formats that need one. Omit for OpenImmo and RESO, which are already standardised.", json_schema_extra={"examples": [{"Kaufpreis": "price", "Objektnummer": "external_id", "Wohnflaeche": "living_area"}]})
    name: StrictStr = Field(description="Your own label for the connector.", json_schema_extra={"examples": ["Nightly listing sync"]})
    schedule: Optional[StrictStr] = Field(default=None, description="How often to pull, for fetched sources. Cron expression in UTC. Ignored for drops and pushes, which run on arrival.", json_schema_extra={"examples": ["15 3 * * *"]})
    __properties: ClassVar[List[str]] = ["deletion_policy", "delivery", "format", "mapping", "name", "schedule"]

    @field_validator('deletion_policy')
    def deletion_policy_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['explicit_only', 'absence_withdraws']):
            raise ValueError("must be one of enum values ('explicit_only', 'absence_withdraws')")
        return value

    @field_validator('format')
    def format_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['csv', 'json']):
            raise ValueError("must be one of enum values ('csv', 'json')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateImportSourceRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateImportSourceRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "deletion_policy": obj.get("deletion_policy") if obj.get("deletion_policy") is not None else 'explicit_only',
            "delivery": obj.get("delivery"),
            "format": obj.get("format"),
            "mapping": obj.get("mapping"),
            "name": obj.get("name"),
            "schedule": obj.get("schedule")
        })
        return _obj


