# coding: utf-8

"""
    Skautik Partner API

    The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreatePropertyRequest(BaseModel):
    """
    CreatePropertyRequest
    """ # noqa: E501
    address: Dict[str, Any] = Field(description="At minimum a city and country; more improves geocoding precision.", json_schema_extra={"examples": [{"city": "Berlin", "country": "DE", "postal_code": "10999", "street": "Oranienstrasse 12"}]})
    currency: StrictStr = Field(description="ISO 4217 code.", json_schema_extra={"examples": ["EUR"]})
    external_id: Optional[StrictStr] = Field(default=None, description="Your identifier for this property. Optional, but set it if the record might later arrive through an import: without one the import has nothing to match on and creates a duplicate.", json_schema_extra={"examples": ["AG-4471-0812"]})
    price: StrictInt = Field(description="Amount in minor units.", json_schema_extra={"examples": [48900000]})
    property_type: StrictStr = Field(description="One of the supported property types.", json_schema_extra={"examples": ["apartment"]})
    title: StrictStr = Field(description="Headline for the listing.", json_schema_extra={"examples": ["Top-floor apartment with a south-facing balcony"]})
    transaction_type: StrictStr = Field(description="sale or rent.", json_schema_extra={"examples": ["sale"]})
    __properties: ClassVar[List[str]] = ["address", "currency", "external_id", "price", "property_type", "title", "transaction_type"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreatePropertyRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreatePropertyRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": obj.get("address"),
            "currency": obj.get("currency"),
            "external_id": obj.get("external_id"),
            "price": obj.get("price"),
            "property_type": obj.get("property_type"),
            "title": obj.get("title"),
            "transaction_type": obj.get("transaction_type")
        })
        return _obj


