# coding: utf-8

"""
    Skautik Partner API

    The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Generation(BaseModel):
    """
    Generation
    """ # noqa: E501
    created_at: datetime
    failure_reason: Optional[StrictStr] = None
    finished_at: Optional[datetime] = None
    id: StrictStr
    image_url: Optional[StrictStr] = None
    kind: StrictStr
    prompt: Optional[StrictStr] = None
    property_id: Optional[StrictStr] = None
    room_type: Optional[StrictStr] = None
    source_image_id: Optional[StrictStr] = None
    status: StrictStr
    style: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["created_at", "failure_reason", "finished_at", "id", "image_url", "kind", "prompt", "property_id", "room_type", "source_image_id", "status", "style"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Generation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Generation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "failure_reason": obj.get("failure_reason"),
            "finished_at": obj.get("finished_at"),
            "id": obj.get("id"),
            "image_url": obj.get("image_url"),
            "kind": obj.get("kind"),
            "prompt": obj.get("prompt"),
            "property_id": obj.get("property_id"),
            "room_type": obj.get("room_type"),
            "source_image_id": obj.get("source_image_id"),
            "status": obj.get("status"),
            "style": obj.get("style")
        })
        return _obj


