# coding: utf-8

"""
    Skautik Partner API

    The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ListingInput(BaseModel):
    """
    ListingInput
    """ # noqa: E501
    commission_amount: Optional[Union[StrictFloat, StrictInt]] = None
    commission_note: Optional[StrictStr] = None
    commission_payer: Optional[StrictStr] = None
    commission_percent: Optional[Union[StrictFloat, StrictInt]] = None
    currency: Optional[StrictStr] = None
    deposit: Optional[Union[StrictFloat, StrictInt]] = None
    heating_costs: Optional[Union[StrictFloat, StrictInt]] = None
    price: Optional[Union[StrictFloat, StrictInt]] = None
    price_on_request: Optional[StrictBool] = None
    price_period: Optional[StrictStr] = None
    service_charges: Optional[Union[StrictFloat, StrictInt]] = None
    status: Optional[StrictStr] = None
    total_rent: Optional[Union[StrictFloat, StrictInt]] = None
    transaction_type: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["commission_amount", "commission_note", "commission_payer", "commission_percent", "currency", "deposit", "heating_costs", "price", "price_on_request", "price_period", "service_charges", "status", "total_rent", "transaction_type"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListingInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListingInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "commission_amount": obj.get("commission_amount"),
            "commission_note": obj.get("commission_note"),
            "commission_payer": obj.get("commission_payer"),
            "commission_percent": obj.get("commission_percent"),
            "currency": obj.get("currency"),
            "deposit": obj.get("deposit"),
            "heating_costs": obj.get("heating_costs"),
            "price": obj.get("price"),
            "price_on_request": obj.get("price_on_request"),
            "price_period": obj.get("price_period"),
            "service_charges": obj.get("service_charges"),
            "status": obj.get("status"),
            "total_rent": obj.get("total_rent"),
            "transaction_type": obj.get("transaction_type")
        })
        return _obj


