# coding: utf-8

"""
    Skautik Partner API

    The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from skautik.models.address import Address
from skautik.models.building import Building
from skautik.models.energy import Energy
from skautik.models.image import Image
from skautik.models.listing import Listing
from skautik.models.location import Location
from skautik.models.market_context import MarketContext
from skautik.models.price_observation import PriceObservation
from skautik.models.rooms import Rooms
from skautik.models.size import Size
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ModelProperty(BaseModel):
    """
    ModelProperty
    """ # noqa: E501
    address: Address
    building: Building
    created_at: datetime
    description: Optional[StrictStr] = None
    energy: Optional[Energy] = None
    external_id: Optional[StrictStr] = None
    id: StrictStr
    images: Optional[List[Image]] = None
    last_verified_at: Optional[datetime] = None
    listing: Optional[Listing] = None
    location: Optional[Location] = None
    market: Optional[MarketContext] = None
    price_history: Optional[List[PriceObservation]] = None
    rooms: Rooms
    size: Size
    source: StrictStr
    title: StrictStr
    type: StrictStr
    updated_at: datetime
    __properties: ClassVar[List[str]] = ["address", "building", "created_at", "description", "energy", "external_id", "id", "images", "last_verified_at", "listing", "location", "market", "price_history", "rooms", "size", "source", "title", "type", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModelProperty from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of building
        if self.building:
            _dict['building'] = self.building.to_dict()
        # override the default output from pydantic by calling `to_dict()` of energy
        if self.energy:
            _dict['energy'] = self.energy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in images (list)
        _items = []
        if self.images:
            for _item_images in self.images:
                if _item_images:
                    _items.append(_item_images.to_dict())
            _dict['images'] = _items
        # override the default output from pydantic by calling `to_dict()` of listing
        if self.listing:
            _dict['listing'] = self.listing.to_dict()
        # override the default output from pydantic by calling `to_dict()` of location
        if self.location:
            _dict['location'] = self.location.to_dict()
        # override the default output from pydantic by calling `to_dict()` of market
        if self.market:
            _dict['market'] = self.market.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in price_history (list)
        _items = []
        if self.price_history:
            for _item_price_history in self.price_history:
                if _item_price_history:
                    _items.append(_item_price_history.to_dict())
            _dict['price_history'] = _items
        # override the default output from pydantic by calling `to_dict()` of rooms
        if self.rooms:
            _dict['rooms'] = self.rooms.to_dict()
        # override the default output from pydantic by calling `to_dict()` of size
        if self.size:
            _dict['size'] = self.size.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModelProperty from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": Address.from_dict(obj["address"]) if obj.get("address") is not None else None,
            "building": Building.from_dict(obj["building"]) if obj.get("building") is not None else None,
            "created_at": obj.get("created_at"),
            "description": obj.get("description"),
            "energy": Energy.from_dict(obj["energy"]) if obj.get("energy") is not None else None,
            "external_id": obj.get("external_id"),
            "id": obj.get("id"),
            "images": [Image.from_dict(_item) for _item in obj["images"]] if obj.get("images") is not None else None,
            "last_verified_at": obj.get("last_verified_at"),
            "listing": Listing.from_dict(obj["listing"]) if obj.get("listing") is not None else None,
            "location": Location.from_dict(obj["location"]) if obj.get("location") is not None else None,
            "market": MarketContext.from_dict(obj["market"]) if obj.get("market") is not None else None,
            "price_history": [PriceObservation.from_dict(_item) for _item in obj["price_history"]] if obj.get("price_history") is not None else None,
            "rooms": Rooms.from_dict(obj["rooms"]) if obj.get("rooms") is not None else None,
            "size": Size.from_dict(obj["size"]) if obj.get("size") is not None else None,
            "source": obj.get("source"),
            "title": obj.get("title"),
            "type": obj.get("type"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


