# coding: utf-8

"""
    Skautik Partner API

    The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from skautik.models.problem_errors_inner import ProblemErrorsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Problem(BaseModel):
    """
    An RFC 9457 problem document, returned by every failure.
    """ # noqa: E501
    code: Optional[StrictStr] = Field(default=None, description="A stable identifier to branch on, unlike the prose.", json_schema_extra={"examples": ["not_found"]})
    detail: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["No property with that id, or one belonging to another organisation."]})
    errors: Optional[List[ProblemErrorsInner]] = Field(default=None, description="Field-level problems, when the failure is a validation one.")
    request_id: Optional[StrictStr] = Field(default=None, description="Quote this when asking about a specific failure.", json_schema_extra={"examples": ["req_8f2a41c9d0"]})
    status: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [404]})
    title: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["Not found"]})
    type: Optional[StrictStr] = Field(default=None, description="A link to the documentation for this failure.", json_schema_extra={"examples": ["https://skautik.com/developers/docs/errors#not_found"]})
    __properties: ClassVar[List[str]] = ["code", "detail", "errors", "request_id", "status", "title", "type"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Problem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in errors (list)
        _items = []
        if self.errors:
            for _item_errors in self.errors:
                if _item_errors:
                    _items.append(_item_errors.to_dict())
            _dict['errors'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Problem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "code": obj.get("code"),
            "detail": obj.get("detail"),
            "errors": [ProblemErrorsInner.from_dict(_item) for _item in obj["errors"]] if obj.get("errors") is not None else None,
            "request_id": obj.get("request_id"),
            "status": obj.get("status"),
            "title": obj.get("title"),
            "type": obj.get("type")
        })
        return _obj


