# coding: utf-8

"""
    Skautik Partner API

    The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from skautik.models.listing_input import ListingInput
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PropertyInput(BaseModel):
    """
    PropertyInput
    """ # noqa: E501
    address_city: Optional[StrictStr] = None
    address_country: Optional[StrictStr] = None
    address_district: Optional[StrictStr] = None
    address_number: Optional[StrictStr] = None
    address_postal_code: Optional[StrictStr] = None
    address_province: Optional[StrictStr] = None
    address_street: Optional[StrictStr] = None
    bathrooms: Optional[StrictInt] = None
    bedrooms: Optional[StrictInt] = None
    condition: Optional[StrictStr] = None
    construction_type: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    energy_consumption_kwh: Optional[Union[StrictFloat, StrictInt]] = None
    energy_label: Optional[StrictStr] = None
    external_id: Optional[StrictStr] = None
    floor: Optional[StrictInt] = None
    floors_in_building: Optional[StrictInt] = None
    half_bathrooms: Optional[StrictInt] = None
    heating_type: Optional[StrictStr] = None
    latitude: Optional[Union[StrictFloat, StrictInt]] = None
    listing: Optional[ListingInput] = None
    living_area_sqm: Optional[Union[StrictFloat, StrictInt]] = None
    location_precision: Optional[StrictStr] = None
    longitude: Optional[Union[StrictFloat, StrictInt]] = None
    plot_area_sqm: Optional[Union[StrictFloat, StrictInt]] = None
    title: Optional[StrictStr] = None
    total_rooms: Optional[StrictInt] = None
    type: Optional[StrictStr] = None
    usable_area_sqm: Optional[Union[StrictFloat, StrictInt]] = None
    year_built: Optional[StrictInt] = None
    year_renovated: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["address_city", "address_country", "address_district", "address_number", "address_postal_code", "address_province", "address_street", "bathrooms", "bedrooms", "condition", "construction_type", "description", "energy_consumption_kwh", "energy_label", "external_id", "floor", "floors_in_building", "half_bathrooms", "heating_type", "latitude", "listing", "living_area_sqm", "location_precision", "longitude", "plot_area_sqm", "title", "total_rooms", "type", "usable_area_sqm", "year_built", "year_renovated"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PropertyInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of listing
        if self.listing:
            _dict['listing'] = self.listing.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PropertyInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address_city": obj.get("address_city"),
            "address_country": obj.get("address_country"),
            "address_district": obj.get("address_district"),
            "address_number": obj.get("address_number"),
            "address_postal_code": obj.get("address_postal_code"),
            "address_province": obj.get("address_province"),
            "address_street": obj.get("address_street"),
            "bathrooms": obj.get("bathrooms"),
            "bedrooms": obj.get("bedrooms"),
            "condition": obj.get("condition"),
            "construction_type": obj.get("construction_type"),
            "description": obj.get("description"),
            "energy_consumption_kwh": obj.get("energy_consumption_kwh"),
            "energy_label": obj.get("energy_label"),
            "external_id": obj.get("external_id"),
            "floor": obj.get("floor"),
            "floors_in_building": obj.get("floors_in_building"),
            "half_bathrooms": obj.get("half_bathrooms"),
            "heating_type": obj.get("heating_type"),
            "latitude": obj.get("latitude"),
            "listing": ListingInput.from_dict(obj["listing"]) if obj.get("listing") is not None else None,
            "living_area_sqm": obj.get("living_area_sqm"),
            "location_precision": obj.get("location_precision"),
            "longitude": obj.get("longitude"),
            "plot_area_sqm": obj.get("plot_area_sqm"),
            "title": obj.get("title"),
            "total_rooms": obj.get("total_rooms"),
            "type": obj.get("type"),
            "usable_area_sqm": obj.get("usable_area_sqm"),
            "year_built": obj.get("year_built"),
            "year_renovated": obj.get("year_renovated")
        })
        return _obj


