# coding: utf-8

"""
    Skautik Partner API

    The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SearchPropertiesRequest(BaseModel):
    """
    SearchPropertiesRequest
    """ # noqa: E501
    bounds: Optional[Dict[str, Any]] = Field(default=None, description="Rectangle with sw_lat, sw_lng, ne_lat, ne_lng. Mutually exclusive with polygon.", json_schema_extra={"examples": [{"east": 13.4791, "north": 52.5401, "south": 52.4812, "west": 13.3702}]})
    filters: Optional[Dict[str, Any]] = Field(default=None, description="Same keys the list endpoint accepts as query parameters.", json_schema_extra={"examples": [{"price_max": 60000000, "property_type": "apartment"}]})
    limit: Optional[StrictInt] = Field(default=50, description="Results to return, 1 to 200.", json_schema_extra={"examples": [50]})
    polygon: Optional[List[StrictStr]] = Field(default=None, description="Closed ring of [longitude, latitude] pairs, GeoJSON order.", json_schema_extra={"examples": [[[13.3702, 52.4812], [13.4791, 52.4812], [13.4791, 52.5401], [13.3702, 52.5401], [13.3702, 52.4812]]]})
    query: Optional[StrictStr] = Field(default=None, description="Plain-language description of what is wanted.", json_schema_extra={"examples": ["\"quiet two bedroom near a park, needs a home office\""]})
    __properties: ClassVar[List[str]] = ["bounds", "filters", "limit", "polygon", "query"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchPropertiesRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchPropertiesRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bounds": obj.get("bounds"),
            "filters": obj.get("filters"),
            "limit": obj.get("limit") if obj.get("limit") is not None else 50,
            "polygon": obj.get("polygon"),
            "query": obj.get("query")
        })
        return _obj


