# coding: utf-8

"""
    Skautik Partner API

    The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Size(BaseModel):
    """
    Size
    """ # noqa: E501
    attic_sqm: Optional[Union[StrictFloat, StrictInt]] = None
    balcony_terrace_sqm: Optional[Union[StrictFloat, StrictInt]] = None
    cellar_sqm: Optional[Union[StrictFloat, StrictInt]] = None
    garden_sqm: Optional[Union[StrictFloat, StrictInt]] = None
    living_area_sqm: Optional[Union[StrictFloat, StrictInt]] = None
    office_area_sqm: Optional[Union[StrictFloat, StrictInt]] = None
    other_area_sqm: Optional[Union[StrictFloat, StrictInt]] = None
    plot_area_sqm: Optional[Union[StrictFloat, StrictInt]] = None
    retail_area_sqm: Optional[Union[StrictFloat, StrictInt]] = None
    storage_area_sqm: Optional[Union[StrictFloat, StrictInt]] = None
    total_area_sqm: Optional[Union[StrictFloat, StrictInt]] = None
    usable_area_sqm: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["attic_sqm", "balcony_terrace_sqm", "cellar_sqm", "garden_sqm", "living_area_sqm", "office_area_sqm", "other_area_sqm", "plot_area_sqm", "retail_area_sqm", "storage_area_sqm", "total_area_sqm", "usable_area_sqm"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Size from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Size from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "attic_sqm": obj.get("attic_sqm"),
            "balcony_terrace_sqm": obj.get("balcony_terrace_sqm"),
            "cellar_sqm": obj.get("cellar_sqm"),
            "garden_sqm": obj.get("garden_sqm"),
            "living_area_sqm": obj.get("living_area_sqm"),
            "office_area_sqm": obj.get("office_area_sqm"),
            "other_area_sqm": obj.get("other_area_sqm"),
            "plot_area_sqm": obj.get("plot_area_sqm"),
            "retail_area_sqm": obj.get("retail_area_sqm"),
            "storage_area_sqm": obj.get("storage_area_sqm"),
            "total_area_sqm": obj.get("total_area_sqm"),
            "usable_area_sqm": obj.get("usable_area_sqm")
        })
        return _obj


